
exports.up = async function(knex) {
    const inclusions =
        [ 
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Weeding'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Pruning'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Mulching'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Hedging'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Fertilising'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Inspect & Trim Tree Branches in Contact with House'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Remove Green Waste'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Remove Annuals'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Pest Control'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Dead Head Annuals'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Divide herbaceous clumping plants'},
            {service_id: 1, inclusion_type: 'main', has_frequency: true, label: 'Turn & Distribute Compost'},
            {service_id: 1, inclusion_type: 'scope', has_value: true, label: 'Maximum Land Size (mtrs/sq)'},
            {service_id: 1, inclusion_type: 'scope', has_value: true, label: 'Number of Garden Beds'},
            {service_id: 1, inclusion_type: 'scope', has_value: true, label: 'Number of hedges'},
            {service_id: 1, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra landsize'},
            {service_id: 1, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra Hedges'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Mopping'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Vacuuming'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Dusting'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Bathrooom Cleaning'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Kitchen Cleaning'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Interior Window Cleaning'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Hard Surface Disinfection'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Floor Sweeping'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Oven Cleaning'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Stove Cleaning'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Inspect/Empty House Vacuum Containers'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Carpet Cleaning / Steam Cleaning'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Lint Removal from Dryer'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Sanitise Sinks, Handles'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Clear Drains'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'General Tidying'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Laundry Clean'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Curtains'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Fridge Cleaning'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Ironing'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Carpet Pile Lifting'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Carpet Stain Removal'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Clean Mirrors'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Vacuum Rugs'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Clean Microwave'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Scrub & Clean Toilets'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Scrub & Clean Showers & Baths'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Scrub & Clean Sinks'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Vaccuum Couches'},
            {service_id: 2, inclusion_type: 'main', has_frequency: true, label: 'Dust Ceiling Fans'},
            {service_id: 2, inclusion_type: 'scope', has_value: true, label: 'Number of Bathrooms'},
            {service_id: 2, inclusion_type: 'scope', has_value: true, label: 'Number of Kitchens'},
            {service_id: 2, inclusion_type: 'scope', has_value: true, label: 'Number of Bedrooms'},
            {service_id: 2, inclusion_type: 'scope', has_value: true, label: 'Number of Loungerooms'},
            {service_id: 2, inclusion_type: 'scope', has_value: true, label: 'Number of Rugs'},
            {service_id: 2, inclusion_type: 'scope', has_value: true, label: 'Number of Fridges'},
            {service_id: 2, inclusion_type: 'scope', has_value: true, label: 'Number of Windows'},
            {service_id: 2, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra Bedrooms'},
            {service_id: 2, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra Bathrooms'},
            {service_id: 2, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra Kitchens'},
            {service_id: 2, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra Loungerooms'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Check / Replace Light Bulbs'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Smoke / CO Alarm Test & Battery Replacement'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Clean Gutters'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Check & Repair Leaking Taps'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect/Repair Tub & Shower Caulking'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect, Repair & Seal Grout in Tiled Areas'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect & Clean Drains'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect & Repair Toilets'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect & Repair Counter / Bench Caulking'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Replace Drinking Water Filters'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Clean Dryer Vent'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Service Doors / Hinges / Locks'},
            {service_id: 3, inclusion_type: 'main', has_value: true, has_frequency: true, label: '"X" Hours of general Handyman tasks from Optional List (Below)'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect/Lubricate Sliding Door Tracks'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Drain 2 Litres from Water Heater (check PTR valve, remove accumulated sediment)'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect/Clean HVAC Filters'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect/Repair Sink Caulking'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Operate/Lubricate Bath Ventilation Fans'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Add Freshener To Refrigerator'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Add Freshener To Dishwasher'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect/Repair Exterior Caulking'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Clean Garbage Disposal Unit'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Lint removal from Dryer'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Oil Garage Door Opener'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Vacuum / Clean Fridge Coils'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Clean Range Hood & Extractor Fan'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect Clean Tap Aerators'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Flyscreens Inspect / Repair'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Inspect Service Life of Fire Extinguishers'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Wash Home Exterior'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Exterior Window Cleaning'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Test Garage Door Auto-Reverse Safety Feature'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Remove Showerhead - Clean Sediment'},
            {service_id: 3, inclusion_type: 'main', has_frequency: true, label: 'Electrical Safety Residual Current Device Test (RCD) - advise to engage electrician if requiring repair'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'High pressure Hosing (Deck, Furniture, Driveway, Paving etc.)'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'Tile Repair'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'Wall Patching / Repair'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'Furniture / Flatpack Assembly'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'Appliance Install'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'Deck Oiling'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'Picture Hanging'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'Outdoor Furniture Oiling'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'Fence & Gate Repair'},
            {service_id: 3, inclusion_type: 'addon', has_frequency: true, label: 'Small Paint Jobs - Interior & Exterior'},
            {service_id: 3, inclusion_type: 'scope', has_value: true, label: 'Number of Bedrooms'},
            {service_id: 3, inclusion_type: 'scope', has_value: true, label: 'Number of Bathrooms'},
            {service_id: 3, inclusion_type: 'scope', has_value: true, label: 'Hours for tasks from Optional Inclusions list'},
            {service_id: 3, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra hours of tasks from Optional Task list'},
            {service_id: 3, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra bedrooms'},
            {service_id: 3, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra bathrooms'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Lawn Mowing'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Edging'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Aeration'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Fertilising'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Reseed Bare Patches'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Weeding'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Treat Lawn Pests / Grubs'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Rake Fallen Leaves'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Remove Green Waste'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Top Dress'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'De-thatch'},
            {service_id: 4, inclusion_type: 'main', has_frequency: true, label: 'Check Soil PH'},
            {service_id: 4, inclusion_type: 'scope', has_value: true, label: 'Land size (mtrs/sq)'},
            {service_id: 4, inclusion_type: 'scope', has_value: true, label: 'Additional Lawns'},
            {service_id: 4, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra land size (mtrs/sq)'},
            {service_id: 4, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Additional lawns'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Skim Leaves & Debris'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Chemistry Sample & Adjustment'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Salt Water Cell Clean'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Skimmer Basket Cleaning'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Pump Basket Clean'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Brush Sediment off Walls'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Inspect Valves'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Check Filter, Backwash'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Maintain / Service Auto Pool Cleaner'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Algaecide as required'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Lubricate Fittings, Valves'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Top Up Water as Required'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Inspect for Cracks, Tears, Required repairs'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Winterize'},
            {service_id: 5, inclusion_type: 'main', has_frequency: true, label: 'Open Up for Summer'},
            {service_id: 5, inclusion_type: 'scope', has_value: true, label: 'Size of pool - mtrs'},
            {service_id: 5, inclusion_type: 'scope', has_value: true, label: 'size of pool - litres'},
            {service_id: 5, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra meters '},
            {service_id: 5, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra litres'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Trim'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Clipping'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Wash'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Dry'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Flea Treatment'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Detangling & Removing Matted Har'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Cleaning Ears'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Brushing Teeth'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Checking for Parasites'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Trimming Nails'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Checking for Skin Conditions'},
            {service_id: 6, inclusion_type: 'main', has_frequency: true, label: 'Expressing anal sacs'},
            {service_id: 6, inclusion_type: 'scope', has_value: true, label: 'Number of Dogs'},
            {service_id: 6, inclusion_type: 'scope', has_value: true, label: 'Dog Size (kgs)'},
            {service_id: 6, inclusion_type: 'scope', has_value: true, label: 'Short hair'},
            {service_id: 6, inclusion_type: 'scope', has_value: true, label: 'Long Hair'},
            {service_id: 6, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra Dog from same house'},
            {service_id: 6, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Long Hair'},
            {service_id: 7, inclusion_type: 'main', has_frequency: true, label: 'Walk'},
            {service_id: 7, inclusion_type: 'main', has_frequency: true, label: 'Play'},
            {service_id: 7, inclusion_type: 'main', has_frequency: true, label: 'Off-Leash Time'},
            {service_id: 7, inclusion_type: 'main', has_frequency: true, label: 'Dog Park Visit'},
            {service_id: 7, inclusion_type: 'main', has_frequency: true, label: 'Group Dog Walking'},
            {service_id: 7, inclusion_type: 'main', has_frequency: true, label: 'Individual Dog Walking'},
            {service_id: 7, inclusion_type: 'scope', has_value: true, label: 'Number of Dogs'},
            {service_id: 7, inclusion_type: 'scope', has_value: true, label: 'Dog Size (kgs)'},
            {service_id: 7, inclusion_type: 'scope', has_value: true, label: 'Minutes walk'},
            {service_id: 7, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra dog from same house'},
            {service_id: 8, inclusion_type: 'main', has_frequency: true, label: 'Firewood Supply'},
            {service_id: 8, inclusion_type: 'main', has_frequency: true, label: 'Stacking'},
            {service_id: 8, inclusion_type: 'main', has_frequency: true, label: 'Kindling Supply'},
            {service_id: 8, inclusion_type: 'main', has_frequency: true, label: 'Delivery'},
            {service_id: 8, inclusion_type: 'main', has_frequency: true, label: 'Type of Wood'},
            {service_id: 8, inclusion_type: 'main', has_frequency: true, label: 'Cut / Split'},
            {service_id: 8, inclusion_type: 'scope', has_value: true, label: 'm3'},
            {service_id: 8, inclusion_type: 'scope', has_value: true, label: 'Split'},
            {service_id: 8, inclusion_type: 'scope', has_value: true, label: 'Stacked'},
            {service_id: 8, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra m3'},
            {service_id: 9, inclusion_type: 'main', has_frequency: true, label: 'Chimney Clean'},
            {service_id: 9, inclusion_type: 'main', has_frequency: true, label: 'Fireplace Inspection'},
            {service_id: 9, inclusion_type: 'main', has_frequency: true, label: 'Chimney Inspection'},
            {service_id: 9, inclusion_type: 'main', has_frequency: true, label: 'Remove Creosite'},
            {service_id: 9, inclusion_type: 'main', has_frequency: true, label: 'Slow Combustion Fireplace Glass Clean'},
            {service_id: 9, inclusion_type: 'scope', has_value: true, label: 'Number of fireplaces'},
            {service_id: 9, inclusion_type: 'scope', has_value: true, label: 'Number of chimneys'},
            {service_id: 9, inclusion_type: 'scope', has_value: true, label: 'Number of levels'},
            {service_id: 9, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra Fireplace'},
            {service_id: 9, inclusion_type: 'upgrade', has_price: true, has_value: true, label: 'Extra level'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Car Wash'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Interior Clean'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Vacuum'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Polish'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Wheel Wash'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Tyre Shine'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Check Tyre Pressure'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Replace Windscreen Wipers'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Top-up Wiper Bottle Levels'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Dashboard & Console Clean'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Gentle Hand Dry'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Upholstery Seats Shampoo'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Mats Shampoo'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Leather Seats Clean & Conditioning'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Carpet Shampoo'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Deoderised'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Windows; Exterior & Interior'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Door Panels & Frames'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Hard Surface Sanitisation'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Mirrors Clean'},
            {service_id: 10, inclusion_type: 'main', has_frequency: true, label: 'Clay Bar Treatment'},
            {service_id: 10, inclusion_type: 'scope', has_value: true, label: 'Number of cars'},
            {service_id: 10, inclusion_type: 'scope', has_value: true, label: 'Number of 4WD`s'},
            {service_id: 10, inclusion_type: 'scope', has_value: true, label: 'Number of SUV`s'},
        ]

    await knex('service_inclusions').del()
    await knex('service_inclusions').insert(inclusions)

    const frequencies = [
        { id: 10, label: 'Weekly', description: 'per week' },
        { id: 20, label: 'Bi-Weekly', description: 'every other week' },
        { id: 30, label: 'Monthly', description: 'per month' },
        { id: 40, label: 'Quarterly', description: 'per quarter' },
        { id: 50, label: 'Annually', description: 'per year' },
    ]

    await knex('frequencies').del()
    await knex('frequencies').insert(frequencies)
}

exports.down = async function(knex) {
  
}
